Repository projectsyn/component-cert-exporter, pull requests merged in 2023-02, with the labels that each got.

#24 Increase default CPU limits for cert-exporter
  class/defaults.yml
  tests/golden/defaults/cert-exporter/cert-exporter/10_helmchart/x509-certificate-exporter/templates/daemonset.yaml
  tests/golden/defaults/cert-exporter/cert-exporter/10_helmchart/x509-certificate-exporter/templates/deployment.yaml
Labels: enhancement

#8 Update dependency quay.io/enix/x509-certificate-exporter to v2.13.0
  class/defaults.yml
  tests/golden/defaults/cert-exporter/cert-exporter/10_helmchart/x509-certificate-exporter/templates/daemonset.yaml
  tests/golden/defaults/cert-exporter/cert-exporter/10_helmchart/x509-certificate-exporter/templates/deployment.yaml
Labels: dependency

#25 Fix default CPU limit for cert-exporter v2.13.0
  class/defaults.yml
  tests/golden/defaults/cert-exporter/cert-exporter/10_helmchart/x509-certificate-exporter/templates/deployment.yaml
Labels: bug
