Repository projectsyn/component-cert-exporter, pull requests merged in 2023-10, with the labels that each got.

#34 Update Helm release x509-certificate-exporter to v3.10.1
  class/defaults.yml
  tests/golden/defaults/cert-exporter/cert-exporter/10_helmchart/x509-certificate-exporter/templates/clusterrole.yaml
  tests/golden/defaults/cert-exporter/cert-exporter/10_helmchart/x509-certificate-exporter/templates/clusterrolebinding.yaml
  tests/golden/defaults/cert-exporter/cert-exporter/10_helmchart/x509-certificate-exporter/templates/daemonset.yaml
  tests/golden/defaults/cert-exporter/cert-exporter/10_helmchart/x509-certificate-exporter/templates/deployment.yaml
  tests/golden/defaults/cert-exporter/cert-exporter/10_helmchart/x509-certificate-exporter/templates/service.yaml
  tests/golden/defaults/cert-exporter/cert-exporter/10_helmchart/x509-certificate-exporter/templates/serviceaccount.yaml
  tests/golden/defaults/cert-exporter/cert-exporter/10_helmchart/x509-certificate-exporter/templates/servicemonitor.yaml
Labels: dependency

#36 Make multi-instanciable; Add option to remove OCP cluster monitoring label
  class/defaults.yml
  component/app.jsonnet
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: enhancement

#37 Fix multi instance manifest output
  class/cert-exporter.yml
  component/app.jsonnet
  component/ocpscc.jsonnet
Labels: bug
